version: '3.8'

services:
  nodeapp:
    image: yidadaa/chatgpt-next-web
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: <OPEN_API_SECRET>
      CODE: <CODE>
      HIDE_USER_API_KEY: 1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/chat.example.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/chat.example.com/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - nodeapp
    networks:
      - app-network

networks:
  app-network:
